### ISSUE TITLE
Can CTRXplorer open html file that is on the 3ds SD card? 

### ISSUE THREAD

**Issue by xualen** [d0k3/CTRXplorer#1]

**Comment by d0k3** [comment]
Yes, but it can display it only as hexadecimal numbers. If you meant parsing the HTML and viewing it as a document - no, and a HTML parser goes beyound the scope of CTRXplorer. I might consider a text viewer at a later point.

I think Sunshell has a HTML viewer built in.

 Closing this issue for now.

**Comment by xualen** [comment]
thanks for your replay. i means that can i run offline html file by CTRXplorer to boot rxtools on 3ds ?

**Comment by xualen** [comment]
thanks for your replay.
