### ISSUE TITLE
using Page Up/Page Down in text viewer to go past EOF can crash

### ISSUE THREAD

**Issue by ihaveamac** [d0k3/CTRXplorer#14]
v0.9.5 - if using Page Up/Page Down (L/R) in the text viewer to go past the end of file, CTRXplorer may crash.

3DSX version becomes unresponsive
CIA version force exits to Home Menu, with no error message

New3DS, 10.6.0-31U emunand with AuReiNand

**Comment by d0k3** [comment]
I'll look into it, thanks for the find!

**Comment by d0k3** [comment]
Okay, I guess I could use some more info, cause I have trouble reproducing this issue... can you give me a sample file? Or, perhaps, information about the files for which this is likely to happen? Also, does this happen in wordwrapped mode, in unwrapped mode, or in both?

**Comment by d0k3** [comment]
Nevermind, I think I already got it. Should be fixed in https://github.com/d0k3/CTRXplorer/commit/dbdef0ee72fce81f95735f6b0ea835b675036bd7

This issue only happened with text files smaller than the screen, correct? Should be fixed in any case. If you want to give it a try, download the [compiled files from here](http://wikisend.com/download/105290/).

Leaving this open until you say it is okay now...

**Comment by ihaveamac** [comment]
sorry for the initial lack of information.
- the text file I tried it with had more lines than could fit on the screen. I did try it with a single-line file though and the same result happened.
- word-wrapping on stops me from going past the EOF; off does not.

the file you linked to says it doesn't exist when I try to download (??) and I'm having strange issues trying to build myself:

```
make: *** No rule to make target `/Users/<username>/devkitPro/citrus/tools/make_base'.  Stop.
```

I don't know where to get this, citrus doesn't seem to have it.

**Comment by d0k3** [comment]
Alright, sorry for the wait.

make_base should be included in citrus, there is something strange here. You can download the compiled CTRXplorer (+bugfix) from here, though: http://workupload.com/file/TTm4hUfP

I could reproduce the problem with a single line file (the bugfix fixes that), but not with anything bigger yet.

**Comment by ihaveamac** [comment]
looks good, I can't go past the EOF in a larger text file, and it doesn't crash doing it with a single-line file.

**Comment by d0k3** [comment]
Alright, looking good, closing this. The fix will be in the next release.
