### ISSUE TITLE
can't delete files

### ISSUE THREAD

**Issue by ghost** [d0k3/CTRXplorer#15]
When in 
emunand
latest cia build 
old3ds 9.2U
unlinked nands
inside of the, Nintendo 3ds/id0/id1/.../extdata/ folder:
cannot delete any files saying they don't exist (even though highlighted).

Same exact circumstance in sysnand they delete fine.

**Comment by d0k3** [comment]
Maybe these files are protected by the system? You can delete other files, right? You could try this in GodMode9. On CTRXplorer, maybe have other users / other 3DS consoles check if they have the same issue.

**Comment by ghost** [comment]
Yeah, I was using test files so I think you're right. Do you think there are any rsf flags that can be changed to allow access to extdata deletion? I'll test myself and see if I can find them.

Just so you know, I'm trying to delete the 00000008f folder so I can downgrade to 2.1 (otp retrieval) without the error screen on installing title 0004003000008F02 (home menu). Prefer an elegant solution over having to resume a halted update with rxtools. Yuck. :p

**Comment by d0k3** [comment]
Does this bug still exist, @idgrepthat ?

**Comment by ghost** [comment]
> Does this bug still exist, @idgrepthat ?

It appears that after further tests, I could delete the "opposite" nand's extdata files.
For instance, I could delete sysnand's home menu theme data when in emunand and vice versa. Makes sense: each nand tries to protect it's own files but is helpless to file activity from a different nand. I don't know if you would still consider this an issue, but I'll leave it up to you if this app should be able to delete everything on the sd card regardless of the 3ds's attempt to protect certain files. (and yes, godmode9 deleted extdata files without issue on it's own nand - dat arm9 privilege!)

Anyway, when using luma3ds to downgrade emunand to 2.1, none of this was an issue.

Sorry so late with responding.

**Comment by d0k3** [comment]
Disabling / circumventing may lead to unexpected results, which is not the case with GM9 (cause that doesn't have the whole OS running in the background). I think this is one of those rare cases where you're better off using a SD card reader, instead of relying on some workaround.

What needs to be fixed in any case is the error message given, so I'm leaving this open. Using an SD card reader or GM9 is an acceptable solution, I take it?

**Comment by d0k3** [comment]
Okay, need some help on this again... is the exact error message you get this?
"No such file or directory"

I'll change it to say:
"Permission denied"

... but I first need to know if I got the right one :).

**Comment by ghost** [comment]
Yes, it says exactly:

Deleting failed!
"00000001"
No such file or directory

Press Start to continue.

**Comment by d0k3** [comment]
Finally fixed in https://github.com/d0k3/CTRXplorer/commit/10666f798885a3562c6e7f3ba864497234ddd450

Thanks for the error report!
