### ISSUE TITLE
[Suggestion] Add text file editing

### ISSUE THREAD

**Issue by Ryuzaki-MrL** [d0k3/CTRXplorer#19]
Since CTRXplorer has a text viewer mode and supports the swkbd applet, this could be useful.

**Comment by d0k3** [comment]
Text editing is actually a whole lot more complicated than hex file editing (same as displaying text files is a lot more complicated than displaying hex files). I'll leave that open for now, while I think about it, but as of now, that feature is somewhat unlikely.

**Comment by NinjaBoyLao** [comment]
Can we at least change the hex file editing to implement character-by-character scrolling choice, the way it is (at time of writing) in godmode9? so that us heathens that dont know the hex alphabet dont have to look up what the hex is for each character we want to put

**Comment by d0k3** [comment]
Just so you know, I've seen this, and I'll update CTRXplorer shortly. Text editing won't go in there, but I'll at least provide an easier way for char based changes.

**Comment by NinjaBoyLao** [comment]
Ty, appreciate it

**Comment by d0k3** [comment]
String mode editing in hexviewer added in https://github.com/d0k3/CTRXplorer/commit/cdeab19f3b86458775e5d328f1a81b0f6ff43315
