### ISSUE TITLE
Allow setting/unsetting "Hidden" attribute on files/directories.

### ISSUE THREAD

**Issue by vaguerant** [d0k3/CTRXplorer#21]
It would be great to be able to mark files and directories as hidden on CTRXplorer, for the benefit of homebrew which honors the attribute. This doesn't seem to be doable over SMB, and removing the SD card on a New 3DS XL is a fate worse than death, so I mostly just deal with it. Having a 3DS-side way to manage files in this way would be ideal.

**Comment by d0k3** [comment]
I'll think about this for GM9, but this change won't come for CTRXplorer, sorry.
