### ISSUE TITLE
Add support for viewing text files as text not hex

### ISSUE THREAD

**Issue by gingerbeardman** [d0k3/CTRXplorer#3]
Add support for viewing text files as text not hex

**Comment by d0k3** [comment]
Thinking about this, but can't say for sure if I'll implement this

**Comment by d0k3** [comment]
Added in commit https://github.com/d0k3/CTRXplorer/commit/4d425ba548dfc9e2815799466cba50d665e79670

Testing is appreciated. Release coming soon!
