### ISSUE TITLE
Can't be compiled on CTRUlib v1.0.0

### ISSUE THREAD

**Issue by d0k3** [d0k3/CTRXplorer#4]
Before anyone else opens this: this can't be compiled on CTRUlib 1.0.0 yet, the reason being that ctrcommon is not updated yet. I'm considering using Citrus or trying to replicate all functionality with CTRUlib only - whatever is easier. Ideas are welcome!

**Comment by ghost** [comment]
I'd go with ctrulib but whatever is easier on you :P

**Comment by d0k3** [comment]
Well, that's the point... it is much easier to rewrite with Citrus, and it can be assumed that @SteveIce10 will keep updating this library. In the long run, relying on CTRUlib only would be easier, of course.

Anyway, I've almost decided I will go with Citrus by this point.

**Comment by d0k3** [comment]
Alright, just checked with the latest ctrcommon + ctrulib 1.0.0. Compiles fine. Closing this for now.

**Comment by ghost** [comment]
:+1:
